language: node_js
node_js:
  - "4"
  - "5"
  - "6"

cache: yarn

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn --no-lockfile

script:
  - yarn test
